Revert 60463 - Windows Gateway Data Provider.
Provides the MAC address of any routers connected via Ethernet. Also added in a command line flag to enable it.

Reverting this CL to test if it is responsible for compile failure in 535 branch (cut src@60593), seeing the following error

--------------------Configuration: startup_tests - Release Win32-----------------------
Compiling...
startup_test.cc
shutdown_test.cc
feature_startup_test.cc
Linking...
LINK : warning LNK4224: /OPT:NOWIN98 is no longer supported; ignored
error C2220: warning treated as error - no 'executable' file generated
warning C4743: 'const PollingPolicyInterface::`vftable'' has different size in 'd:\b\slave\chrome-official\build\src\chrome\browser\geolocation\gateway_data_provider_common.cc' and 'd:\b\slave\chrome-official\build\src\chrome\browser\geolocation\wifi_data_provider_win.cc': 12 and 16 bytes
warning C4743: 'const WebKit::WebIDBTransaction::`vftable'' has different size in 'd:\b\slave\chrome-official\build\src\chrome\renderer\renderer_webidbindex_impl.cc' and 'd:\b\slave\chrome-official\build\src\third_party\WebKit\WebKit\chromium\src\WebIDBIndexImpl.cpp': 28 and 32 bytes
warning C4743: 'const WebKit::WebIDBTransaction::`vftable'' has different size in 'd:\b\slave\chrome-official\build\src\chrome\renderer\renderer_webidbobjectstore_impl.cc' and 'd:\b\slave\chrome-official\build\src\third_party\WebKit\WebKit\chromium\src\WebIDBIndexImpl.cpp': 28 and 32 bytes
warning C4743: 'const WebKit::WebIDBTransaction::`vftable'' has different size in 'd:\b\slave\chrome-official\build\src\chrome\renderer\renderer_webidbtransaction_impl.cc' and 'd:\b\slave\chrome-official\build\src\third_party\WebKit\WebKit\chromium\src\WebIDBIndexImpl.cpp': 28 and 32 bytes
Generating code
LINK : fatal error LNK1257: code generation failed
Build log was saved at "file://D:\b\slave\chrome-official\build\src\chrome\Release\obj\startup_tests\BuildLog.htm"
startup_tests - 1 error(s), 1 warning(s)

BUG=None
TEST=None

Review URL: http://codereview.chromium.org/3368014

TBR=allanwoj@chromium.org
Review URL: http://codereview.chromium.org/3509003