Revert 139314 - Merge 138730 - Fetch fresh content url before downloading file from drive.
Broke 1132 branch: 
../../chrome/browser/chromeos/gdata/gdata_parser.cc:614: error: 'kEntryField' was not declared in this scope


This is to ensure the cached content url is not stale.

BUG=128104
TEST=*GData*


Review URL: https://chromiumcodereview.appspot.com/10412049

TBR=tbarzic@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10453058

TBR=satorux@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10440075