Revert of Adding a router class to handle messages that expect responses. (https://codereview.chromium.org/371603003/)
Reason for revert:
This appears to have broken mojotest_instrumentation_tests with the errors like the ones listed below.

http://build.chromium.org/p/chromium.webkit/builders/Android%20Tests%20%28dbg%29/builds/20270

C   52.086s Main  [FAIL] org.chromium.mojo.bindings.ConnectorTest#testErrors:
C   52.086s Main  java.lang.NoClassDefFoundError: java.util.Objects
C   52.086s Main  	at org.chromium.mojo.bindings.MessageHeader.equals(MessageHeader.java:189)
C   52.086s Main  	at org.chromium.mojo.bindings.MessageWithHeader.<init>(MessageWithHeader.java:29)
C   52.086s Main  	at org.chromium.mojo.bindings.MessageWithHeader.<init>(MessageWithHeader.java:39)
C   52.086s Main  	at org.chromium.mojo.bindings.BindingsTestUtils.newRandomMessageWithHeader(BindingsTestUtils.java:85)
C   52.086s Main  	at org.chromium.mojo.bindings.ConnectorTest.setUp(ConnectorTest.java:53)
C   52.086s Main  	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
C   52.086s Main  	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
C   52.086s Main  	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
C   52.086s Main  	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

C   52.091s Main  [CRASH] org.chromium.mojo.bindings.RouterTest#testReceivingViaRouterWithResponse:
C   52.091s Main  Native crash: Segmentation fault

Original issue's description:
> Adding a router class to handle messages that expect responses.
> 
> This also introduce the notion of message header to allow routing.
> 
> R=rmcilroy@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=283767

TBR=qsr
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/392223004