Revert 240653 "Place DevTools WebContents underneath inspected W..."
Broke compilation on Mac ASAN Builder:

../../chrome/browser/ui/cocoa/dev_tools_controller.mm:82:19:error: no matching function for call to 'max'

> Place DevTools WebContents underneath inspected WebContents.
> 
> DevTools window: split width and height are gone, and instead
> contents insets are introduced. These insets are used for layout
> in browser window. Having insets instead of rect allows for faster
> regular-case resize occuring immediately in layout:
> we keep DevTools of the same size and resize the page contents.
> 
> Views: removed SplitView and ContentsContainer, but instead added
> ContentsLayoutManager which layouts DevTools and page contents taking
> insets into account. It also supports active top margin, moved from
> ContentsContainer.
> 
> Mac: removed NSSplitView, but instead added DevToolsContainerView
> which resizes subviews manually taking page insets into account.
> 
> Gtk: removed both contents_vsplit and contents_hsplit, but instead
> added devtools_floating_container which positions page contents
> taking insets into account.
> 
> Next step will remove dock side knowledge from the browser, and leave it
> on frontend only.
> 
> BUG=318751
> 
> Review URL: https://codereview.chromium.org/63173016

TBR=dgozman@chromium.org

Review URL: https://codereview.chromium.org/110063006