Initialize self._wsout.
If websocket_server.py is called with --server stop, it will call
Stop without calling Start, so it claims as follows:
  AttributeError: 'PyWebSocket' object has no attribute '_wsout'

Review URL: http://codereview.chromium.org/545023