Revert 173259, broke win7 tests:
http://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29/builds/13892/steps/content_unittests/logs/GpuSideBlacklisting

GpuDataManagerImplTest.GpuSideBlacklisting: 
browser\gpu\gpu_data_manager_impl_unittest.cc(147): error: Value of: manager->GpuAccessAllowed()
Actual: true
Expected: false
browser\gpu\gpu_data_manager_impl_unittest.cc(150): error: Value of: manager->GetBlacklistedFeatures()
Actual: 4
Expected: GPU_FEATURE_TYPE_WEBGL | GPU_FEATURE_TYPE_ACCELERATED_2D_CANVAS
Which is: 5

> Fix a bug in r173248
> 
> Otherwise it will fail GPU blacklisting.
> 
> BUG=162928,165374
> TEST=manual about:gpu on machines with blacklisted features
> TBR=kbr
> Review URL: https://codereview.chromium.org/11577033

TBR=zmo@google.com
Review URL: https://codereview.chromium.org/11576051