Rolling GYP to r1568. Changes:
- r1568: Reverting accidental change to test/lib/TestGyp.py (from r1567)
- r1567: Speculative fix for mt.exe general error c101008a (The parameter is incorrect).
- r1566: Xcode: Coalesce multiple "copies" sections in the same target with the same "destination" property into the same PBXCopyFilesBuildPhase.

BUG=173052

TBR=scottmg@chromium.org

Review URL: https://codereview.chromium.org/12204002