Fix Clang compilation error on Android in libevent.gyp.
This is part of Chrome for Android upstreaming.

This fixes the following issue we encountered downstream recently due to 'base'
being built for both the host and target but without distinguishing the
compilation flags properly:
third_party/libevent/http.c:561:6: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror]


Review URL: https://chromiumcodereview.appspot.com/10912095