NaCl: Update revision in DEPS, r12372 -> r12397
r12395 changes NaCl's Scons build so that it doesn't clear out
environment variables.  But this allows PYTHONPATH to leak into
browser_tester which causes it to import the wrong common.py module
from somewhere, giving this error:

Traceback (most recent call last):
  File "/Volumes/data/b/build/slave/mac/build/src/ppapi/native_client/tools/browser_tester/browser_tester.py", line 25, in <module>
    import memcheck_analyze
  File "/Volumes/data/b/build/slave/mac/build/src/ppapi/native_client/tools/browser_tester/../../../../tools/valgrind/memcheck_analyze.py", line 34, in <module>
    _BORING_CALLERS = common.BoringCallers(mangled=True, use_re_wildcards=True)
AttributeError: 'module' object has no attribute 'BoringCallers'

Fix this by using sys.path.insert(0, X), usually preferred over
sys.path.append(X).

This pulls in the following Native Client changes:

r12373: (jvoung) Skip building stack_frame.cc and eh_return.c with PNaCl sjlj.
r12374: (mcgrathr) toolchain_build: Update gcc revision
r12375: (thakis) Remove scons-related stuff from gyp.
r12376: (jvoung) Update PNaCl in TOOL_REVISIONS from 12331 -> 12372
r12377: (mcgrathr) Update ARM toolchain in TOOL_REVISIONS
r12378: (jfb) libpnaclmm: fix the compare-exchange implementation.
r12379: (jfb) Run libc++ tests on FYI bots, add lit known failures
r12380: (mcgrathr) Disable static build ID collection code for dynamic linking
r12381: (sbc) Add stubs for tcgetattr/tcsetattr/etc to libnacl.
r12382: (mcgrathr) Deploy new x86 binutils
r12383: (mcgrathr) Fix nacl.scons test of coverage mode
r12384: (mseaborn) PNaCl: Fix failure in archived-toolchain tests introduced by r12364
r12385: (nfullagar) Revert 12382 "Deploy new x86 binutils"
r12386: (jfb) Mark Clang::CodeGen/atomics-inlining.c as broken.
r12387: (yyanagisawa) Enables goma from GYP and GOMA_DIR env.
r12388: (nfullagar) Add win8 to nacl trybots.
r12389: (jfb) Fix newlib build for iconv so that we support UTF-16LE and UCS-4LE.
r12390: (dschuff) Fix 2 problems with parsing and checking of LLVM test results
r12391: (mseaborn) PNaCl: Update libcxxabi revision in pnacl/COMPONENT_REVISIONS
r12392: (jfb) Update newlib revision to pull in 'Update newlib so that it passes libc++'s tests.'
r12393: (dschuff) PNaCl: Update LLVM revision in pnacl/COMPONENT_REVISIONS
r12394: (dschuff) Add svn:ignore property for toolchain_build/src
r12395: (bradnelson) Rely on the environment to provide a usable python on windows
r12396: (yyanagisawa) Revert r12387: "Enables goma from GYP and GOMA_DIR env."
r12397: (mseaborn) PNaCl: Update LLVM and libstdc++ (GCC) revisions for SJLJ EH info format change

BUG=319585
TEST=browser_tests and nacl_integration

Review URL: https://codereview.chromium.org/74083005