When NEON disabled, always build ARM memset routines.
Fixes:
...SkUtils_opts_arm.cpp:36:error: undefined reference to 'arm_memset16'
...SkUtils_opts_arm.cpp:53:error: undefined reference to 'arm_memset32'

BUG=155921,277433
TEST=Fixes missing memset routine during linking.
R=mtklein@google.com, reed@google.com

Review URL: https://codereview.chromium.org/391793002