Fixed content_browsertest isolate: webgl_conformance removed.
https://codereview.chromium.org/104723003 broke the content browsertests
on Android with

MappingError: /b/build/slave/Android_Tests__JB_GalaxyNexus__dbg_/
build/src/third_party/webgl_conformance/ is not a directory but
ends with "/"

This patch should fix that.

R=zmo@chromium.org,maruel@chromium.org
BUG=326173

Review URL: https://codereview.chromium.org/108083002