Disable PrepopulateRespectBlack interactive_ui_test
Becomes flaky in Aura windows

browser\ui\views\find_bar_host_interactive_uitest.cc(222): error: Value of: GetFindBarText()
  Actual: L""
Expected: ASCIIToUTF16("a")
Which is: L"a"


BUG=292299
TEST=none
TBR=sky

Review URL: https://codereview.chromium.org/24129007