Revert 236927 "Reorganize media::VideoCapture* types"
Failing compile on win and win x64

FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\media\video\capture\win\media.capability_list_win.obj.rsp /c ..\..\media\video\capture\win\capability_list_win.cc /Foobj\media\video\capture\win\media.capability_list_win.obj /Fdobj\media\media.pdb 
c:\b\build\slave\cr-win-rel-x64\build\src\media\video\capture\win\capability_list_win.h(54) :error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\b\build\slave\cr-win-rel-x64\build\src\media\video\capture\win\capability_list_win.h(54) : warning C4183: 'DISALLOW_COPY_AND_ASSIGN': missing return type; assumed to be a member function returning 'int'
ninja: build stopped: subcommand failed.

> Reorganize media::VideoCapture* types
> 
> The purpose of this CL is to clean up the distinction between
> VideoCaptureFormat (which identifies the captured type of a frame),
> VideoCaptureParams (which identifies the requested format of a capture),
> and VideoCaptureCapability (which identifies the capture capabilities of a
> device).
> 
> Notably:
> * VideoCaptureFormat::frame_size_type ->
>   VideoCaptureParams::allow_resolution_change, as variable resolution
>   capability is a per-session, not a per-frame property.
> * VideoCaptureCapability::color -> VideoCaptureFormat::pixel_format, as frame
>   color format is a per-frame property.
>   * As VideoCaptureParams holds a VideoCaptureFormat member, capture requests
>     are able now to request a particular capture color format.
> 
> BUG=269312
> TEST=local build, run unittests, chrome on CrOS snow, desktop Linux
> 
> Review URL: https://codereview.chromium.org/68503005

TBR=sheu@chromium.org

Review URL: https://codereview.chromium.org/84393002