Revert 125942.
This is a really cool change, but it appears it wasn't tested
well enough and the tree wasn't attended after landing it.
It turns tests on several bots on several platforms (win, mac, chromeos)
red. Some of the failing tests failed on the tryjobs for this CL, too.

A list of failing tests:
OutOfProcessPPAPITest.View_PageHideShow: 
.\test\ui\ppapi_uitest.cc(913): error: Value of: observer.result().c_str()
  Actual: "PageHideShow FAIL: Didn't receive a hide event in timeout. NOTE: This test requires tab visibility to change and won't pass if you just run it in a browser. Normally the UI test should handle this. You can also run manually by waiting 2 secs, creating a new tab, waiting 2 more secs, and closing the new tab."
Expected: "TestPageHideShow:Created"

PPAPINaClTest.PostMessage_SendingArrayBuffer: 
[2256:3984:0309/201351:810562:ERROR:external_registry_extension_loader_win.cc(84)] Missing value path for key Software\Google\Chrome\Extensions\jfmjfhklogoienhpfnppmbcbjfjnkonk.
Killed (timed out).

PPAPITest.NetAddressPrivate_DescribeIPv6: 
Did not complete.

See also http://crbug.com/117641

- Switch PPAPITests to run in browser_tests instead of ui_tests. The former is sharded and so tests run in parallel. Before this they were taking 17 minutes on the trybot. Now they take about a minute.

Another benefit is we can replace the sleeps with messages, so hopefully this makes the test faster/less flakier.

BUG=115595
Review URL: https://chromiumcodereview.appspot.com/9646027

TBR=jam@chromium.org
Review URL: https://chromiumcodereview.appspot.com/9664034