Fix a crash in record_wpr when a tab crashes.
Stack trace:

Traceback (most recent call last):
  File "tools/perf/record_wpr", line 13, in <module>
    sys.exit(record_wpr.Main(benchmark_dir))
  File "/home/default/skia-repo/buildbot/third_party/chromium_trunk/tools/telemetry/telemetry/page/record_wpr.py", line 107, in Main
    '\n'.join(results.errors) + '\n'.join(results.failures))
TypeError: sequence item 0: expected string, tuple found

Looks like maybe introduced in: https://codereview.chromium.org/15231002

I am not sure this is the best solution, feedback will be appreciated.

Review URL: https://chromiumcodereview.appspot.com/15894009