compile.py: need re.escape for gomacc path
if we don't escape, we got error
Traceback (most recent call last):
  File "..\..\..\scripts\slave\compile.py", line 1169, in <module>
    sys.exit(real_main())
  File "..\..\..\scripts\slave\compile.py", line 1165, in real_main
    return main(options, args)
  File "..\..\..\scripts\slave\compile.py", line 809, in main_ninja
    new_build.write(cc_line_pattern.sub(goma_repl, line))
  File "E:\b\depot_tools\python_bin\lib\re.py", line 273, in _subx
    template = _compile_repl(template, pattern)
  File "E:\b\depot_tools\python_bin\lib\re.py", line 260, in _compile_repl
    raise error, v # invalid expression
  sre_constants.error: bad group name
because windows path uses \ as path separater.

TBR=maruel@chromium.org
Review URL: https://codereview.chromium.org/11272024