Revert 229640 "Break the dependency BackTexture had on the entir..."
Broke compilation on linux chromeos:

../../gpu/command_buffer/service/gles2_cmd_decoder.cc:5760:39:error: too few arguments to function ‘void gpu::gles2::RestoreCurrentTexture2DBindings(gpu::gles2::ContextState*)’


> Break the dependency BackTexture had on the entire Decoder.
> 
> BUG=
> 
> Review URL: https://codereview.chromium.org/27762003

TBR=kloveless@chromium.org

Review URL: https://codereview.chromium.org/30823002