Revert "Be explicit about what buildslave to import instead of fishing around."
This change causes Buildbot 0.8 slaves to fail to connect:

Traceback (most recent call last):
  File "run_slave.py", line 471, in <module>
    main()
  File "run_slave.py", line 444, in main
    HotPatchSlaveBuilder(is_testing)
  File "run_slave.py", line 158, in HotPatchSlaveBuilder
    Log('HotPatchSlaveBuilder(%s)' % is_testing)
  File "run_slave.py", line 54, in Log
    from buildbot.slave.bot import log
ImportError: No module named buildbot.slave.bot
make: *** [start] Error 1

This reverts commit 155900.

TBR=maruel@chromium.org

Review URL: https://chromiumcodereview.appspot.com/10919205