Revert Goma switch for WebRTC Windows bots.
In https://codereview.chromium.org/197873038/
all WebRTC client buildbots were switched to Goma.
Despite local testing, the buildbots failed with
errors like this:

[119/3002] CC obj\third_party\libjpeg_turbo\libjpeg.jcdctmgr.obj
FAILED: ninja -t msvc -e environment.x86 -- E:\b\build\goma\gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\third_party\expat\files\lib\expat.xmltok.obj.rsp /c ..\..\third_party\expat\files\lib\xmltok.c /Foobj\third_party\expat\files\lib\expat.xmltok.obj /Fdobj\third_party\expat\expat.c.pdb
e:\b\build\slave\win\build\src\third_party\expat\files\lib\xmltok_impl.c(103) : fatal error C1090: PDB API call failed, error code '23' : '(

BUG=None
TEST=None
TBR=stip

Review URL: https://codereview.chromium.org/208683005