Revert 258779 "sync: Shrink ProfileSyncServiceHarness (retry)"
Same problem as before (with r258666, reverted r258674). E.g.,

FAILED: c++ -MMD -MF obj/chrome/browser/sync/test/integration/performance/sync_performance_tests.sync_timing_helper.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_MOJO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DUSE_XI2_MT=2 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_INPUT_SPEECH -DENABLE_NOTIFICATIONS -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_AUTOMATION=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DHAS_OUT_OF_PROC_TEST_RUNNER -DGL_GLEXT_PROTOTYPES -DLIBPEERCONNECTION_LIB=1 -DGTEST_HAS_POSIX_RE=0 -DNACL_WINDOWS=0 -DNACL_LINUX=1 -DNACL_OSX=0 -DNACL_TARGET_SUBARCH=64 -DNACL_TARGET_ARCH=x86 -DNACL_BUILD_SUBARCH=64 -DNACL_BUILD_ARCH=x86 -DAUTOFILL_ENABLE_SYNC -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DLINUX -DPOSIX -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DUSE_NSS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -I../.. -Iobj/chrome/sync_performance_tests.gen -Igen/protoc_out -I../../skia/config -I../../third_party/khronos -I../../gpu -I../../third_party/WebKit/Source -Igen -I../../third_party/WebKit -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../testing/gtest/include -I../../third_party -I../../third_party/webrtc -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/protobuf -I../../third_party/protobuf/src -I../../testing/gmock/include -I../../net/third_party/nss/ssl -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare  -c ../../chrome/browser/sync/test/integration/performance/sync_timing_helper.cc -o obj/chrome/browser/sync/test/integration/performance/sync_performance_tests.sync_timing_helper.o
../../chrome/browser/sync/test/integration/performance/sync_timing_helper.cc: In static member function 'static base::TimeDelta SyncTimingHelper::TimeSyncCycle(ProfileSyncServiceHarness*)':
../../chrome/browser/sync/test/integration/performance/sync_timing_helper.cc:20:3: error: 'AwaitCommitActivityCompletion' was not declared in this scope

> sync: Shrink ProfileSyncServiceHarness (retry)
> 
> The first attempt at this change, r258666, had to be reverted because it
> triggered a compile failure on the buildbots.  Apparently the build bots
> still build the sync performance tests, while the try bots do not.
> 
> Original commit message follows.
> 
> Reduces the number of tasks for which the ProfileSyncServiceHarness is
> responsible.
> 
> The goal here is to clean up some organizational issues that are left
> over from the old ProfileSyncServiceHarness design.  Now that the
> harness no longer needs to be in control of everything, we can start to
> shrink it down to a more appropriate size.
> 
> Highlights inlcude:
> - Move the responsibility for observing the ProfileSyncService to the
>   StatusChangeCheckers.  PSSHarness is no longer a PSSObserver, and no
>   longer implements AwaitStatusChange().
> - Move responsibility for initializing P2P invalidations to the sync
>   tests.  The PSSHarness no longer owns the invalidations forwarder
>   and no longer takes a reference to the InvalidationService.
> - Move AwaitPassphraseRequired, AwaitPassphraseAccepted and
>   AwaitCommitActivityCompletion into sync_integration_test_util.h.
>   There was no need for them to depend on the harness.  Unlike some
>   other functions that were refactored, these were used in several
>   different tests, so they were moved to a util file to encourage
>   code sharing.
> - Hide some Await functions that are only used inside the harness,
>   such as AwaitSyncSetupCompletion() and AwaitBackendInitialized().
> - Move some encryption functionality into sync_test.cc.
> - Convert several functions to use ProfileSyncService* parameters,
>   rather than ProfileSyncServiceHarness*.
> 
> TBR=tim@chromium.org,dcheng@chromium.org
> BUG=323380
> 
> Review URL: https://codereview.chromium.org/196173010

TBR=rlarocque@chromium.org

Review URL: https://codereview.chromium.org/208423008