Revert of Moving binutils version extraction so it works with clang. (https://codereview.chromium.org/199333007/)
Reason for revert:
Seems to break runhooks on several bots, like:
http://build.chromium.org/p/chromium.memory/builders/Linux%20ASan%2BLSan%20Builder/builds/1188

Error: Command /usr/bin/python src/build/gyp_chromium returned non-zero exit status 1 in /b/build/slave/Linux_ASan_LSan_Builder/build
Updating projects from gyp files...
/bin/sh: 1: clang++: not found
compiler_version.py failed to execute: clang++ -Xassembler --version -x assembler -c /dev/null
Command 'clang++ -Xassembler --version -x assembler -c /dev/null' returned non-zero exit status 127
gyp: Call to 'python ../build/compiler_version.py assembler' returned exit status 1.

Original issue's description:
> Moving binutils version extraction so it works with clang.
> 
> BUG=352046
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=257943

TBR=thestig@chromium.org,thakis@chromium.org,mithro@mithis.com
NOTREECHECKS=true
NOTRY=true
BUG=352046

Review URL: https://codereview.chromium.org/203603009