This patch fixes following compilation introduced by r202702 on VS2012
d:\src\w\crbk\src\chrome\nacl\nacl_listener.cc(149) : error C2220: warning treated as error - no 'object' file generated
d:\src\w\crbk\src\chrome\nacl\nacl_listener.cc(149) : warning C4703: potentially uninitialized local pointer variable 'ipc_fd' used

NOTRY=true
TBR=ncbray@chromium.org
BUG=n/a

Review URL: https://codereview.chromium.org/16107003