Linux: use -Wl,--no-as-needed on 32-bit builders.
This is needed to fix a linking error on Ubuntu Precise:
/usr/bin/ld: out/Debug/obj.target/sync/libsync.so: undefined reference to symbol 'SSL_ExportKeyingMaterial'
/usr/bin/ld: note: 'SSL_ExportKeyingMaterial' is defined in DSO out/Debug/obj.target/net/third_party/nss/libcrssl.so so try adding it to the linker command line
out/Debug/obj.target/net/third_party/nss/libcrssl.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make: *** [out/Debug/unit_tests] Error 1

TBR=thestig

BUG=170262

Review URL: https://codereview.chromium.org/12633012