Revert 203308 "[Sync] Split GetPreferredTypes into GetActiveType..."
Possibly broke lots of sync related tests on Win Aura Tests (2):

[----------] 1 test from SyncSetupHandlerTestWithParam/SyncSetupHandlerTest
[ RUN      ] SyncSetupHandlerTestWithParam/SyncSetupHandlerTest.TurnOnEncryptAll/1

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: IsManaged()
          Returns: false
Stack trace:

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: HasSyncSetupCompleted()
          Returns: false
Stack trace:

GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: DisableForUser()
Stack trace:

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: sync_initialized()
          Returns: false
Stack trace:

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: HasSyncSetupCompleted()
          Returns: false
Stack trace:

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: IsSyncEnabledAndLoggedIn()
          Returns: false
Stack trace:

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: IsManaged()
          Returns: false
Stack trace:

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: EncryptEverythingEnabled()
          Returns: false
Stack trace:

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: IsManaged()
          Returns: false
Stack trace:
c:\b\build\slave\win_aura_builder\build\src\chrome\browser\ui\webui\sync_setup_handler_unittest.cc(965): error: Actual function call count doesn't match EXPECT_CALL(*mock_pss_, EnableEncryptEverything())...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] SyncSetupHandlerTestWithParam/SyncSetupHandlerTest.TurnOnEncryptAll/1, where GetParam() = false (125 ms)
[----------] 1 test from SyncSetupHandlerTestWithParam/SyncSetupHandlerTest (141 ms total)

> [Sync] Split GetPreferredTypes into GetActiveTypes and GetPreferredTypes
> 
> GetPreferredDataTypes was being used as an accessor for getting the set of
> active types. This has now been split into its own method, GetActiveDataTypes,
> and GetPreferredDataTypes now just returns what the name implies, the set of
> preferred types.
> 
> BUG=none
> TBR=brettw@chromium.org, kinuko@chromium.org, dbeam@chromium.org
> 
> Review URL: https://chromiumcodereview.appspot.com/14789020

TBR=zea@chromium.org

Review URL: https://codereview.chromium.org/15979011