Revert "cc: Cleanup vertex shaders used for anti-aliasing."
This reverts commit 6cfd71b7734d21322f71d9639396392c92ad0ee3.

This broke the win7 bot:

LayerTreeHostFiltersPixelTest.BackgroundFilterBlurOffAxis:
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(180)]
Percentage of pixels with an error: 0.0125
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(182)]
Percentage of pixels with errors not greater than 1: 0.0125
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(185)] Average
absolute error (excluding identical pixels): R=0.4 G=1 B=0.4 A=0
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(190)] Largest
absolute error: R=1 G=1 B=1 A=0
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(205)] Pixel
error at x=23 y=75; actual RGBA=(147,147,147,255); expected
RGBA=(146,146,146,255)
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(205)] Pixel
error at x=24 y=97; actual RGBA=(186,186,186,255); expected
RGBA=(185,185,185,255)
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(205)] Pixel
error at x=101 y=71; actual RGBA=(0,70,0,255); expected
RGBA=(0,71,0,255)
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(205)] Pixel
error at x=109 y=75; actual RGBA=(0,54,0,255); expected
RGBA=(0,55,0,255)
[8388:8392:0508/084355:938938:ERROR:pixel_comparator.cc(205)] Pixel
error at x=147 y=94; actual RGBA=(11,48,11,255); expected
RGBA=(11,49,11,255)
test\layer_tree_pixel_test.cc(61): error: Value of:
MatchesPNGFile(*bitmap, test_data_dir.Append(ref_file_),
*pixel_comparator_)
Actual: false
Expected: true

Your try results showed the same failure.

R=reveman@chromium.org
TBR=reveman@chromium.org
BUG=238644

Review URL: https://codereview.chromium.org/15027017