Revert 213664 "Fix archive build for git."
Failed on Linux x64:
http://build.chromium.org/p/chromium/builders/Linux%20x64/builds/53438/steps/archive_build/logs/stdio

chromium_utils.CopyFileToDir(src/out/Release/remoting-webapp.v2.zip, /b/build/slave/Linux_x64/chrome_staging/, dest_fn=remoting-webapp.v2.zip)
chromium_utils.CopyFileToDir(src/out/Release/remoting-webapp.zip, /b/build/slave/Linux_x64/chrome_staging/, dest_fn=remoting-webapp.zip)
Traceback (most recent call last):
  File "../../../scripts/slave/chromium/archive_build.py", line 751, in <module>
      sys.exit(main(None))
        File "../../../scripts/slave/chromium/archive_build.py", line 747, in main
      return s.ArchiveBuild()
        File "../../../scripts/slave/chromium/archive_build.py", line 574, in ArchiveBuild
            self._GenerateChangeLog(previous_revision, changelog_path)
        File "../../../scripts/slave/chromium/archive_build.py", line 458, in _GenerateChangeLog
            self._chromium_revision)
        File "../../../scripts/slave/chromium/archive_build.py", line 82, in _GetChangeLog
            last_revision, current_revision)
              File "../../../scripts/slave/chromium/archive_build.py", line 56, in _GetXMLChangeLogByModule
	    '--xml', '-r', '%d:%d' % (last_revision + 1, current_revision)]
	    TypeError: %d format: a number is required, not str

> Fix archive build for git.
> 
> Even though there were already nice methods for getting SVN or Git revisions,
> archive_build was only using the SVN one, causing master.chromium.git to fail.
> 
> This is a resubmission of https://codereview.chromium.org/19059003/, because it
> was reverted in https://codereview.chromium.org/19067005/. This incorporates a
> new change to the way GitOrSvn determines if it is in a Git or Svn repo which
> allows it to work for git repos without breaking svn repos like the first one
> did.
> 
> R=szager@chromium.org,maruel@chromium.org
> 
> Review URL: https://chromiumcodereview.appspot.com/20149005

TBR=agable@chromium.org

Review URL: https://codereview.chromium.org/20430002