Fix a lint issue with ActivityContentVideoViewClient.java.
Currently, the lint warns at:
Error: Field requires API level 16 (current min is 14):
    android.view.View#SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION [InlinedApi]
Error: Field requires API level 16 (current min is 14):
    android.view.View#SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN [InlinedApi]
Error: Field requires API level 16 (current min is 14):
    android.view.View#SYSTEM_UI_FLAG_FULLSCREEN [InlinedApi]

So we need to add @SuppressLint("InlinedApi") to suppress these lint errors.

BUG=327768

Review URL: https://codereview.chromium.org/305333002