Revert 199008 "Fixes a memory leak when running webrtc-internals..."
> Fixes a memory leak when running webrtc-internals for a long time, by using a circular buffer of size 1k for stats data points. Also explicitly draws the graph time labels 1min apart in a 5min range.
> 
> BUG=230250
> 
> Review URL: https://chromiumcodereview.appspot.com/14880002

This was causing timeoutes on linux asan bots. Here's output for one:

WebRTCInternalsBrowserTest.BweCompoundGraph: 
[20315:20315:0508/145009:557958908:ERROR:zygote_host_impl_linux.cc(144)]
Running without the SUID sandbox! See
https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment
for more information on developing with the sandbox on.
Right after fork
Right before base::type_profiler::Controller::Stop()
Right after base::type_profiler::Controller::Stop()
Right after signal/exception handler restoration.
Right after fd_shuffle push_backs.
Right after ShuffleFileDescriptors
Right after CloseSuperfluousFds
Right before execvp
[20315:20330:0508/145010:558032619:WARNING:proxy_service.cc(889)] PAC
support disabled because there is no system implementation
HTTP server started on 127.0.0.1:46138...
sending server_data: {"host": "127.0.0.1", "port": 46138} (36 bytes)
[20315:20315:0508/145010:558307838:ERROR:CONSOLE(964)] "Uncaught
ReferenceError: singleReport is not defined", source:
chrome://webrtc-internals/webrtc_internals.js (964)
Killed (timed out).


TBR=jiayl@chromium.org

Review URL: https://codereview.chromium.org/15021010