add missing dependency for r242160
Fixes

d:\src\cr3\src\third_party\skia\include\ports\sktypeface_win.h(11) : fatal error C1083: Cannot open include file: 'SkTypeface.h': No such file or directory

on 1700 branch. I think this is strictly speaking missing on trunk too,
but something else pulls in the dependency. So I'm just going to fix it
on the branch.

TBR=karen@chromium.org

Review URL: https://codereview.chromium.org/106433008