Revert 213636 "Switch Chromium to use Blink's blink_resources.grd"
Broke the build with:
error: 'gen/webkit/webkit_chromium_resources.pak', needed by 'DumpRenderTree.pak', missing and no known rule to make it

> Switch Chromium to use Blink's blink_resources.grd
> 
> WebKit.grd is deprecated, so we update it public/blink_resources.grd.
> 
> R=darin@chromium.org, joth@chromium.org, thestig@chromium.org
> 
> Review URL: https://codereview.chromium.org/19537010

TBR=tfarina@chromium.org

Review URL: https://codereview.chromium.org/20341002