Linux: add an option to use system libsrtp
This requires a recent CVS snapshot, and build
with vanilla libsrtp-1.4.4 fails:

third_party/libjingle/source/talk/session/media/srtpfilter.cc: In member function 'bool cricket::SrtpSession::SetKey(int, const std::string&, const uint8*, int)':
third_party/libjingle/source/talk/session/media/srtpfilter.cc:571:10: error: 'struct srtp_policy_t' has no member named 'window_size'
third_party/libjingle/source/talk/session/media/srtpfilter.cc:572:10: error: 'struct srtp_policy_t' has no member named 'allow_repeat_tx'

BUG=none
TEST=none
Review URL: https://codereview.chromium.org/11198045