Revert 88271, this broke the clang build thusly:
chrome/browser/chromeos/login/screen_locker.cc:225:16:error: 'ClearNativeFocus' marked 'override' but does not override any member functions
  virtual void ClearNativeFocus() OVERRIDE {
               ^
  CXX(target) out/Debug/obj.target/browser/chrome/browser/chromeos/login/take_photo_view.o
1 error generated.

Looks like a real bug in the CL.

88271 - Wait showing html dialog until renderre finish painting after page is loaded.
 This change keeps track of state transition to make sure we only show the window on the paint after page load.

minor change; use gdk's debug paint. Views no longer manage the damaged rect by itself so we can simply use gdk's debug paint.

Note to mazda. Please consider adding fade-in animation. I believe it will make it much nicer.

BUG=chromium-os:15809
TEST=open keyboard overlay on device. no white flicker should be observed.

Review URL: http://codereview.chromium.org/7024032

TBR=oshima@google.com
Review URL: http://codereview.chromium.org/6995067