Revert "Switch isolate recipe module to use bundled find_isolated_test.py script."
This reverts commit 9331576d925307f2d1036c91d9c24fb87c2bb8ff.

It broke GPU testers on tryserver.chromium.gpu/builders/linux_gpu_triggered_tests:
Traceback (most recent call last):
  ...
  File "/b/build/scripts/slave/recipe_modules/isolate/api.py", line 141, in runtest
    args=self.runtest_args_list(test, args),
  File "/b/build/scripts/slave/recipe_modules/isolate/api.py", line 120, in runtest_args_list
    isolate_hash = self.isolated_tests[test]
TypeError: string indices must be integers

BUG=354057

Review URL: https://codereview.chromium.org/205583002