Revert "Adding webrtc-internal DEPS"
This reverts commit b8a428f5e60efc87719578f301ebd0a96db8e3a5.

Broke master_test.py presubmit check.
          File "/media/ssd/code/build/masters/master.client.webrtc/master.cfg", line 29, in <module>
            category='trunk')
          File "/media/ssd/code/build/masters/master.client.webrtc/master_win_cfg.py", line 64, in ConfigureBuilders
            F('win32_debug_factory', win().WebRTCFactory(
          File "/media/ssd/code/build/masters/master.client.webrtc/master_win_cfg.py", line 14, in win
            branch, custom_deps_list)
          File "/media/ssd/code/build/scripts/master/factory/webrtc_factory.py", line 42, in __init__
            if config.Master.webrtc_internal_url:
        exceptions.AttributeError: type object 'Master' has no attribute 'webrtc_internal_url'


TBR=nsylvain

Review URL: https://chromiumcodereview.appspot.com/11280195