[Android] Fix compilation error: unused variable 'kAllowedToAccessOnNonjoinableThread'
While building with clang=1, clang reports this error about the above variable being unused.

BUG=349521
NOTRY=true

Review URL: https://codereview.chromium.org/188003002