Fix gclient.py so that save_pinned_deps works.
Chromium OS continuous builds are failing because of the following error.

Traceback (most recent call last):
  File "/b/depot_tools/gclient.py", line 1212, in <module>
    sys.exit(Main(sys.argv[1:]))
  File "/b/depot_tools/gclient.py", line 1202, in Main
    return command(parser, argv[1:])
  File "/b/depot_tools/gclient.py", line 1122, in CMDrevinfo
    client.PrintRevInfo()
  File "/b/depot_tools/gclient.py", line 776, in PrintRevInfo
    url = entries.pop(name)
KeyError: 'chromiumos'

This change will fix the error.

TEST=none
BUG=none
Review URL: http://codereview.chromium.org/2892007