Revert of Remove the id field of inspector_backend since no public caller uses it (https://codereview.chromium.org/322553003/)
Reason for revert:
Apparently it was used somewhere:

http://chromegw/i/chromium.perf/builders/Android%20GN%20Perf/builds/1776/steps/blink_perf/logs/stdio

Traceback (most recent call last):
  _RunPage at tools/telemetry/telemetry/page/page_runner.py:521
    page_state.ImplicitPageNavigation(test)
  ImplicitPageNavigation at tools/telemetry/telemetry/page/page_runner.py:175
    test.RunNavigateSteps(self.page, self.tab)
  RunNavigateSteps at tools/telemetry/telemetry/page/page_test.py:259
    page.RunNavigateSteps(action_runner)
  RunNavigateSteps at tools/telemetry/telemetry/page/page.py:42
    action_runner.NavigateToPage(self)
  NavigateToPage at tools/telemetry/telemetry/page/actions/action_runner.py:63
    self.RunAction(NavigateAction(attributes))
  RunAction at tools/telemetry/telemetry/page/actions/action_runner.py:20
    action.RunActionAndMaybeWait(self._tab)
  RunActionAndMaybeWait at tools/telemetry/telemetry/page/actions/page_action.py:37
    self.RunAction(tab)
  RunAction at tools/telemetry/telemetry/page/actions/navigate.py:22
    tab.Navigate(self.url, script_to_evaluate_on_commit)
  Navigate at tools/telemetry/telemetry/core/tab.py:257
    self._inspector_backend.Navigate(url, script_to_evaluate_on_commit, timeout)
  Navigate at tools/telemetry/telemetry/core/backends/chrome/inspector_backend.py:161
    self._page.Navigate(url, script_to_evaluate_on_commit, timeout)
  Navigate at tools/telemetry/telemetry/core/backends/chrome/inspector_page.py:109
    self.WaitForNavigate(timeout)
  WaitForNavigate at tools/telemetry/telemetry/core/backends/chrome/inspector_page.py:85
    self._inspector_backend.DispatchNotifications(remaining_time)
  DispatchNotifications at tools/telemetry/telemetry/core/backends/chrome/inspector_websocket.py:68
    self._Receive(timeout)
  _Receive at tools/telemetry/telemetry/core/backends/chrome/inspector_websocket.py:108
    self._error_handler(elapsed_time)
  _HandleError at tools/telemetry/telemetry/core/backends/chrome/inspector_backend.py:238
    if self._IsInspectable():
  _IsInspectable at tools/telemetry/telemetry/core/backends/chrome/inspector_backend.py:215
    return self.id in [c['id'] for c in contexts]
AttributeError: 'InspectorBackend' object has no attribute 'id'

Locals:
  contexts : [{u'url': u'http://127.0.0.1:48700/XMLHttpRequest/send.html', u'title': u'127.0.0.1:48700/XMLHttpRequest/send.html', u'type': u'page', u'description': u'', u'id': u'432A3A74-D6DE-77B0-9358-3780FA59FA70'}]


Original issue's description:
> Remove the id field of inspector_backend since no public caller uses it
> 
> TBR=nduca@chromium.org
> 
> BUG=
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=275541

TBR=nednguyen@google.com
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/323713002