GTTF: Use shutil.rmtree in chromium_utils.RemoveDirectory to prevent an error on Windows:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\src\buildbot\scripts\common\chromium_utils.py", line 276, in RemoveDirectory
    remove_with_retry(os.rmdir, os.path.join(root, name))
  File "C:\src\buildbot\scripts\common\chromium_utils.py", line 241, in RemoveWithRetry_win
    return rmfunc(path)
WindowsError: [Error 145] The directory is not empty: 'C:/src/buildbot/slave/chromium-win-experimental/build\\src\\chrome\\test\\live_sync\\.svn'
elapsedTime=130.724000
program finished with exit code 1

Please note that we are still walking the directory tree bottom-up,
it's just that for some reason shutil.rmtree is needed here.

TEST=none
BUg=none
Review URL: http://codereview.chromium.org/3335009