Revert r166725 "Enforce 15 minutes timeout for all operations and 30 minutes..."
This causes an excepiton on Windows,
  File "E:\b\depot_tools\subprocess2.py", line 341, in communicate
TypeError: Using timeout and shell simultaneously will cause a process leak
since the shell will be killed instead of the child process.

TBR=petermayo@chromium.org
BUG=


Review URL: https://chromiumcodereview.appspot.com/11368148