Try to fix a NoneType error on an internal windows bot.
Possibly caused by https://codereview.chromium.org/93933006 . Speculative fix.

Traceback (most recent call last):
  File "..\..\..\scripts\slave\compile.py", line 1201, in <module>
    sys.exit(real_main())
  File "..\..\..\scripts\slave\compile.py", line 1197, in real_main
    return main(options, args)
  File "..\..\..\scripts\slave\compile.py", line 871, in main_win
    sln = open(os.path.join(options.build_dir, options.solution), 'rU')
  File "C:\b\depot_tools\python276_bin\lib\ntpath.py", line 73, in join
    elif isabs(b):
  File "C:\b\depot_tools\python276_bin\lib\ntpath.py", line 57, in isabs
    s = splitdrive(s)[1]
  File "C:\b\depot_tools\python276_bin\lib\ntpath.py", line 125, in splitdrive
    if p[1:2] == ':':
TypeError: 'NoneType' object has no attribute '__getitem__'
program finished with exit code 1

Move the default-initialization code for options.solution in front of its
first use.

TBR=maruel@chromium.org

Review URL: https://codereview.chromium.org/105943009