Revert 131539 - Roll DEPS to pick up new safebrowsing test suite.
This is a speculative revert for update failures on a number of bots.
I apologize for any undue inconvenience if this isn't at fault. Example of errors:
http://build.chromium.org/p/chromium/buildstatus?builder=XP%20Tests%20%282%29&number=13966
Error: Command svn update E:\b\build\slave\XP_Tests__2_\build\src\third_party\pylib --revision 7955 --non-interactive --force --accept theirs-conflict --ignore-externals returned non-zero exit status 1 in E:\b\build\slave\XP_Tests__2_\build

Note that safe_browsing_tests is currently disabled due to flakiness (crbug.com/96459), but this roll will allow the test to be updated for the switch from MACing to SSL.

BUG=119662
TEST=none


Review URL: http://codereview.chromium.org/10024053

TBR=bryner@chromium.org
Review URL: https://chromiumcodereview.appspot.com/9960064