Fix lint issues with Chromoting for Android.
Currently, the lint warns at:
Error: Field requires API level 18 (current min is 14):
    android.provider.Settings#EXTRA_ACCOUNT_TYPES [InlinedApi]
Error: Field requires API level 16 (current min is 14):
    android.view.View#SYSTEM_UI_FLAG_FULLSCREEN [InlinedApi]

So we need to add @TargetApi to suppress these lint error.

BUG=327768

Review URL: https://codereview.chromium.org/273313003