Revert 178037
It broke android.

> Fix official builder compile error when building aura on windows
> 
> The error is in the chrome_frame_common project
> chrome_frame_automation.cc (833) : error C2440: '=' cannot convert from HWND to gfx::NativeWindow
> 
> That is because in aura the gfx::NativeWindow is a aura::Window* instead of HWND
> 
> BUG=171018
> TEST=see bug
> Review URL: https://codereview.chromium.org/12022038

TBR=cpu@chromium.org
Review URL: https://codereview.chromium.org/12035027