Revert of Split Ppapi compositor test to three subtests to avoid timeout. (https://codereview.chromium.org/350183007/)
Reason for revert:
This broke tsan compile:

http://build.chromium.org/p/chromium.memory.fyi/builders/Linux%20Builder%20%28TSan%20v2%29/builds/22158

../../chrome/test/ppapi/ppapi_browsertest.cc:1259:26: error: unknown type name 'Compositor0'; did you mean 'ui::Compositor'?
TEST_PPAPI_NACL_SUBTESTS(MAYBE_Compositor0, RUN_COMPOSITOR_SUBTESTS_0)
                         ^~~~~~~~~~~~~~~~~
                         ui::Compositor
../../chrome/test/ppapi/ppapi_browsertest.cc:1255:27: note: expanded from macro 'MAYBE_Compositor0'
#define MAYBE_Compositor0 Compositor0

The compiler error is several pages long due to all the macro stuff, so I can't quickly see how to fix this, sorry.

Original issue's description:
> Split Ppapi compositor test to three subtests to avoid timeout.
> 
> BUG=387915
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=279531

TBR=dmichael@chromium.org,penghuang@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=387915

Review URL: https://codereview.chromium.org/350963002