Revert 172038 > google_apis: Rename DocumentFeed to ResourceList > > DocumentFeed was a misnomer, as this class represented a resource list. > > Along the way, add more useful comments in gdata_wapi_parser.h, and > fix wrong variable names like 'doc'. > > > BUG=164090 > TEST=none > > > Review URL: https://chromiumcodereview.appspot.com/11499006
The CL broke the tree:
../../chrome/browser/chromeos/extensions/file_browser_event_router.h:91:16:error: 'OnDocumentFeedFetched' marked 'override' but does not override any member functions
  virtual void OnDocumentFeedFetched(int num_accumulated_entries) OVERRIDE;

TBR=satorux@chromium.org
Review URL: https://codereview.chromium.org/11503010