Broke the aura compile on Linux and Windows.
out/Release/../../third_party/gold/gold64:
out/Release/obj.target/ash/libash.so:error: undefined reference to
'oak::ShowOakWindow()'

Revert 136217 - ui/oak: Build oak as a component library.

And export ShowOakWindow() function.

R=ben@chromium.org

Review URL: https://chromiumcodereview.appspot.com/10310050

TBR=tfarina@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10389058