Revert r38720 (which merged in WebKit r54521) because of compile failure:
9>Compiling...
6>..\rendering\RenderObject.cpp(1619) : error C2065: 'oldStyle' : undeclared identifier
6>..\rendering\RenderObject.cpp(1619) : error C2227: left of '->position' must point to class/struct/union/generic type