Fix lint issues with GamepadList.java.
Currently, the lint warns at:
Error: Overriding method should call super.onDetachedFromWindow [MissingSuperCall]
Error: Field requires API level 16 (current min is 14):
    android.content.Context#INPUT_SERVICE [InlinedApi]
Error: Class requires API level 16 (current min is 14):
    android.hardware.input.InputManager.InputDeviceListener [NewApi]
Error: Call requires API level 16 (current min is 14):
    android.hardware.input.InputManager#getInputDeviceIds [NewApi]
Error: Call requires API level 16 (current min is 14):
    android.hardware.input.InputManager#registerInputDeviceListener [NewApi]
Error: Call requires API level 16 (current min is 14):
    android.hardware.input.InputManager#unregisterInputDeviceListener [NewApi]

So we need to add @SuppressLint and @TargetApi to suppress these lint errors.

BUG=327768

Review URL: https://codereview.chromium.org/336453002