Revert of Make WebRTC revision available on Chrome perf dashboard (https://codereview.chromium.org/133613002/)
Reason for revert:
Broke the sizes step in chromium builders:

http://build.chromium.org/p/chromium/builders/Linux/builds/46859/steps/sizes/logs/stdio

Traceback (most recent call last):
  File "../../../scripts/slave/runtest.py", line 1572, in <module>
    sys.exit(main())
  File "../../../scripts/slave/runtest.py", line 1544, in main
    result = main_linux(options, args)
  File "../../../scripts/slave/runtest.py", line 1050, in main_linux
    perf_dashboard_id=options.perf_dashboard_id)
  File "/b/build/scripts/slave/annotation_utils.py", line 106, in annotate
    parser_result = results_tracker.evaluateCommand('command')
  File "/b/build/scripts/slave/process_log_utils.py", line 402, in evaluateCommand
    self.PerformanceSummary()
  File "/b/build/scripts/slave/process_log_utils.py", line 177, in PerformanceSummary
    self._FinalizeProcessing()
  File "/b/build/scripts/slave/process_log_utils.py", line 862, in _FinalizeProcessing
    self._CreateSummaryOutput()
  File "/b/build/scripts/slave/process_log_utils.py", line 877, in _CreateSummaryOutput
    data = [self._BuildSummaryJson(graph) + '\n']
  File "/b/build/scripts/slave/process_log_utils.py", line 858, in _BuildSummaryJson
    self._webrtc_revision, self._v8_revision, self._version,
AttributeError: 'GraphingLogProcessor' object has no attribute '_v8_revision'

Original issue's description:
> Make WebRTC revision available on Chrome perf dashboard
> 
> A lot these changes are common to the ones for V8 in
> https://chromiumcodereview.appspot.com/18325010
> 
> BUG=302713
> TEST=scripts/slave/unittests/results_dashboard_test.py
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=246576

TBR=qyearsley@chromium.org,stip@chromium.org,kjellander@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=302713

Review URL: https://codereview.chromium.org/145653002