Revert of Ash:Shelf - Cleanup of Alternate Shelf (part 1) (https://codereview.chromium.org/140323010/)
Reason for revert:
Broke Linux ChromiumOS Builder (dbg):

http://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder%20%28dbg%29/builds/45933/steps/compile/logs/stdio

FAILED: /b/build/goma/gomacc c++ -MMD -MF obj/ash/system/web_notification/ash.web_notification_tray.o.d ....
../../ash/system/web_notification/web_notification_tray.cc: In constructor 'ash::WebNotificationTray::WebNotificationTray(ash::internal::StatusAreaWidget*)':
../../ash/system/web_notification/web_notification_tray.cc:322:7:error: 'UseAlternateShelfLayout' is not a member of 'ash::switches'
../../ui/message_center/message_center_style.h: At global scope:
../../ui/message_center/message_center_style.h:103:15:error: 'message_center::kButtonSeparatorColor' defined but not used [-Werror=unused-variable]
../../ui/message_center/message_center_style.h:104:15:error: 'message_center::kHoveredButtonBackgroundColor' defined but not used [-Werror=unused-variable]
../../ui/message_center/message_center_style.h:111:15:error: 'message_center::kProgressBarBackgroundColor' defined but not used [-Werror=unused-variable]
../../ui/message_center/message_center_style.h:112:15:error: 'message_center::kProgressBarSliceColor' defined but not used [-Werror=unused-variable]
../../ui/message_center/message_center_style.h:43:15:error: 'message_center::settings::kEntrySeparatorColor' defined but not used [-Werror=unused-variable]


Original issue's description:
> Part 1) of cleaning up the code related to the shelf layout, specifically removing all instances of branching related to the 'alternate shelf layout' as this is now the only option.
> Removed the about:flags entry relating to alternate shelf layout.
> 
> A patch will follow to simplify the remaining layout code as it is still a bit of a spaghetti like mess.
> 
> R=jamescook@chromium.org, skuhne@chromium.org
> TBR=miket@chromium.org
> BUG=338429
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=254301

TBR=jamescook@chromium.org,skuhne@chromium.org,harrym@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=338429

Review URL: https://codereview.chromium.org/185143002