Revert 123372 - Adds deps file for content/browser/accessibility/
DumpAccessibilityTreeTest.PlatformTreeDifferenceTest fails:
..\content\browser\accessibility\dump_accessibility_tree_browsertest.cc(106): error: Value of: actual_contents8
  Actual: "|ROLE_SYSTEM_DOCUMENT||IA2_STATE_HORIZONTAL|IA2_STATE_OPAQUE\n|IA2_ROLE_SECTION||IA2_STATE_HORIZONTAL|IA2_STATE_OPAQUE\n"
Expected: expected_contents
Which is: "|ROLE_SYSTEM_DOCUMENT||IA2_STATE_OPAQUE|IA2_STATE_VERTICAL\n|IA2_ROLE_SECTION||IA2_STATE_HORIZONTAL|IA2_STATE_OPAQUE\n"


Revert "Revert 122617 - Adds dump accessibility tree support in Windows."

This reverts commit ca8de581137b34eb04ca8b68186f143d4bea98e8.

BUG=
TEST=


Review URL: http://codereview.chromium.org/9429026

TBR=dtseng@chromium.org
Review URL: https://chromiumcodereview.appspot.com/9454033