Revert of Add a whole-app-list unit test. (https://codereview.chromium.org/210083009/)
Reason for revert:
Broke Linux build.

http://build.chromium.org/p/chromium.linux/builders/Linux%20Builder/builds/29124/steps/compile/logs/stdio

../../ui/app_list/views/app_list_view_unittest.cc:9:39: fatal error: base/strings/string_util.h.: No such file or directory


Original issue's description:
> Add a whole-app-list unit test.
> 
> This establishes a test harness for doing tests that touch on multiple
> parts of the app launcher UI, or that need coverage for the various app
> launcher configurations: Ash or Desktop; regular or experimental
> "landscape" mode.
> 
> It currently just tests displaying and closing the app launcher in its
> default state with a flat (no folders), 2- or 3-page model.
> 
> BUG=169114
> TEST=Added unit tests AppListViewTest{Aura,Desktop}.*
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=260762

TBR=calamity@chromium.org,tapted@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=169114

Review URL: https://codereview.chromium.org/220323005