chromeos: Fix a clang build error in CandidateWindowView.
Clang doesn't like the destructor to be inlined in .h file.

./chrome/browser/chromeos/input_method/candidate_window_view.h:32:3: error: [chromium-style] Complex destructor has an inline body.

The error was caused by crrev.com/110492

TEST=chrome builds
BUG=none

Review URL: http://codereview.chromium.org/8585043