Fix error in Chromium_Win_Ninja_Goma
Traceback (most recent call last):
  File "..\..\..\scripts\slave\compile.py", line 1042, in <module>
    sys.exit(real_main())
  File "..\..\..\scripts\slave\compile.py", line 1038, in real_main
    return main(options, args)
  File "..\..\..\scripts\slave\compile.py", line 716, in main_ninja
    env['PATH'] = os.pathsep.join([options.goma_dir, env['PATH']])
AttributeError: Values instance has no attribute 'goma_dir'

AFAIK, we could not set CC, CXX to "gomacc cl", because $CC, $CXX would
be used in third_party/WebKit/Source/WebCore/bindings/scripts/preprocessor.pm,
which expects CC is gcc.
Instead, we should set CC and CXX in gyp time.

BUG=132157

Review URL: https://chromiumcodereview.appspot.com/10701076