Revert of JavaScript unit test framework for Chrome remote desktop - Part II (https://codereview.chromium.org/351933003/)
Reason for revert:
Appears to have broken http://build.chromium.org/p/chromium.linux/builders/Linux%20Tests/builds/12029/steps/browser_tests/logs/stdio

"isolate" in the error message is suspicious: http://www.chromium.org/developers/testing/isolated-testing

[ RUN      ] QUnitBrowserTestRunner.Remoting_Webapp_Js_Unittest
Xlib:  extension "RANDR" missing on display ":9".
Xlib:  extension "RANDR" missing on display ":9".
[12246:12246:0704/181239:WARNING:password_store_factory.cc(213)] Using basic (unencrypted) store for password storage. See http://code.google.com/p/chromium/wiki/LinuxPasswordStorage for more information about password storage options.
../../chrome/test/remoting/qunit_browser_test_runner.cc:43: Failure
Value of: PathExists(file)
Actual: false
Expected: true
Error: The QUnit test suite </mnt/data/b/build/slave/Linux_Tests/isolate-2014-07-043CUE8r/out/Release/remoting/unittests/unittest.html> does not exist.
[12246:12310:0704/181239:WARNING:raw_channel_posix.cc(214)] recvmsg: Connection reset by peer
[  FAILED  ] QUnitBrowserTestRunner.Remoting_Webapp_Js_Unittest, where TypeParam =  and GetParam() =  (329 ms)


Original issue's description:
> JavaScript unit test framework - Part II
> 
> This change enables running the JavaScript unit test on try bots using the browser test infrastructure.
> 
> To run a QUnit test suite as a browser test.
> 1. include third_party/qunit/src/browser_test_harness.js in your qunit test suite.
> 2. Derive your browser test from QUnitBrowserTestRunner, and call RunTest with the URL of the test suite.
> 3. modify chrome_tests.gypi to add the c++ source of your browser test and add your test suite as a run time dependency of the browser_tests executable
> 
> Summary of changes:
> 1. QUnit_browser_test_runner.h serves as a base class for a QUnit browser test.  It navigates the browser to the QUnit test suite, calls browserTestHarness.run() and listens for the test results.
>  
> 2. browser_test_harness.js serves as a test took on the QUnit test suite.  Using the window.domAutomationController, browser_test_harness.js detects whether it is running under the browser test infrastructure to auto-enable itself and report results back to the browser test.
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=281451

TBR=sergeyu@chromium.org,rmsousa@chromium.org,jamiewalch@chromium.org,anandc@chromium.org,kelvinp@chromium.org
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/372563002