Fixing undefined pthread undefined references in nacl.
This has been failing consistently on Linux Clang (dbg)
http://build.chromium.org/p/chromium.linux/builders/Linux%20Clang%20%28dbg%29/builds/36114/steps/compile/logs/stdio
And one of my CLs has been tickling this on the Linux 64 builder as well.
http://build.chromium.org/p/chromium/builders/Linux%20x64/builds/41425/steps/compile/logs/stdio

With the following error:

init.c:(.text+0x3c): undefined reference to `__libc_setup_tls'
init.c:(.text+0x2e2): undefined reference to `_dl_init_static_tls'
init.c:(.text+0x2ec): undefined reference to `_dl_wait_lookup_done'

It seems that using -lpthread instead of -pthread seems to be causing this
issue, but it is strangely inconsistent (except on linux clang builders).

BUG=none
TBR=binji@chromium.org

Review URL: https://codereview.chromium.org/11411076