Revert 205044 "Compositor reflector, which copies texture onto a..."
This broke CromeOS compile

cc1plus: warnings being treated as errors
../../ash/display/display_info.cc:40:error: this decimal constant is unsigned only in ISO C90
ninja: build stopped: subcommand failed.

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/54421

> Compositor reflector, which copies texture onto another compositor.
> 
> - added GL utility functions to create and copy texture for mirroring
> - made sure we don't create two compositor for the same display.
> - update the mirroring compositor size when the mirror window size
>   changed.
> - fix a bug that was using int for display ID. changed the
>   initial value for faked display id so that we can catch
>   such error early in test.
> 
> 
> BUG=239776
> TEST=added new tests, plus manually on daisy (mirroring now works on daisy)
> 
> Review URL: https://chromiumcodereview.appspot.com/16232013

TBR=oshima@chromium.org
Review URL: https://codereview.chromium.org/16434007